package com.example.voicechanger.model

data class AudioAttrModel(
    var id: String,
    var name: String,
    var pitch: Int,
    var rate: Int,
    var amplify: Float = 0.0f,
    var autoWah: List<Float>? = null,
    var chorus: List<Float>? = null,
    var compressor: List<Float>? = null,
    var distort: List<Float>? = null,
    var echo: List<Float>? = null,
    var echo4: List<Float>? = null,
    var eq2: List<Float>? = null,
    var eq3: List<Float>? = null,
    var filter: List<Float>? = null,
    var flanger: List<Float>? = null,
    var phaser: List<Float>? = null,
    var reverb: List<Float>? = null,
    var rotate: Float = 0.0f,
    var echo1: List<Float>? = null,
    var isPlaying: Boolean = false,
    var isReverse: Boolean = false,
)
